---
- name: Execute ilab command for initial configuration
  become_user: "{{ bastion_role_student_name }}"
  ansible.builtin.command: |
    /home/{{ bastion_role_student_name }}/instructlab/venv/bin/ilab config init --non-interactive

- name: Execute ilab command to download models
  become_user: "{{ bastion_role_student_name }}"
  ansible.builtin.command: |
    /home/{{ bastion_role_student_name }}/instructlab/venv/bin/ilab model download --repository={{ item.repository }} --filename={{ item.filename }} --hf-token={{ bastion_role_huggingface_ro_token }}
  loop: "{{ bastion_role_model_download_list }}"
  retries: 60
  delay: 10
  register: r_ilab_download
  until: r_ilab_download is not failed

- name: Activate virtual environment for {{ bastion_role_student_name }}
  lineinfile:
    dest: /home/{{ bastion_role_student_name }}/.bashrc
    line: "source $HOME/instructlab/venv/bin/activate"
    owner: "{{ bastion_role_student_name }}"