---
- name: Execute ilab command for initial configuration
  ansible.builtin.command: /home/{{ bastion_role_student_name }}/instructlab/venv/bin/ilab config init --non-interactive

- name: Execute ilab command to download Granite
  ansible.builtin.command: |
    /home/{{ bastion_role_student_name }}/instructlab/venv/bin/ilab model download --repository instructlab/granite-7b-lab-GGUF --filename=granite-7b-lab-Q4_K_M.gguf --hf-token "{{ bastion_role_huggingface_ro_token }}"
  retries: 60
  delay: 10
  register: r_ilab_download
  until: r_ilab_download is not failed

- name: Execute ilab command to download Merlinite
  ansible.builtin.command: |
    /home/{{ bastion_role_student_name }}/instructlab/venv/bin/ilab model download --repository instructlab/merlinite-7b-lab-GGUF --filename=merlinite-7b-lab-Q4_K_M.gguf --hf-token "{{ bastion_role_huggingface_ro_token }}"
  register: r_ilab_download
  until: r_ilab_download is not failed

